version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: kelaskaraditya1
      MONGO_INITDB_ROOT_PASSWORD: Aditya1234
    ports:
      - "27018:27017"
    networks:
      - mongo-network
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kelaskaraditya1
      ME_CONFIG_MONGODB_ADMINPASSWORD: Aditya1234
      ME_CONFIG_MONGODB_SERVER: mongo_container
      ME_CONFIG_OPTIONS_EDITORTHEME: dark
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo-network
    restart: always

networks:
  mongo-network:
    driver: bridge
